### ISSUE TITLE
numguess 기능 추가

### ISSUE THREAD

**Issue by 0andme** [0andme/numguess#13]
## TODO

- [x] function으로 기능 나누기
- [x] 게임 반복 기능 추가
- [x] 게임 반복 횟수 정하기
- [x] 게임 스코어 저장 기능 추가하기

## process

- 사용자 입력
- 게임 진행
- 게임 기회 10번. 중간에 맞추면 나가기
- 점수는 10점->1점 주기
