### ISSUE TITLE
필요한 변수 생성하기

### ISSUE THREAD

**Issue by 0andme** [0andme/numguess#6]
#### TODO

- [x] 반복 횟수를 저장하고 있는 repeat_num  변수 생성 
- [x] 문 정보를 담을 door 변수 생성 (염소 0, 스포츠카 1) ex. `doors=[0,0,1]`
- [x] 사용자 선택 변수 생성  초기 값 0  `user_choice=choice()`
- [x]  문을 바꾸지 않았을 때 이긴 횟수 저장 변수 : no_change_win
- [x] 문을 바꿨을 때 이긴 횟수 저장 변수 : change_win
